### ISSUE TITLE
Pair Programing capstone two

### ISSUE THREAD

**Issue by mohametalmeari** [ShaliniNayan/Capstone-Kanban#21]
https://github.com/ShaliniNayan/Capstone-Kanban/projects/1
We are two people working together, me and my partner
Student A: Shalini
Student B: Mohamad

**Comment by ghost** [comment]
Hi Team, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

- [x] Your board is empty. Kindly create tasks as described [here](https://github.com/microverseinc/curriculum-tools-copy-projects) and assign them to yourselves as required in the project

![image](https://github.com/ShaliniNayan/Capstone-Kanban/assets/98453979/b8d5457d-ac12-4ed6-8d11-5743d7f7bf2c)


Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

**Comment by ShaliniNayan** [comment]
Thank you & Noted

**Comment by prolajumokeoni** [comment]
Hi @ShaliniNayan and @mohametalmeari, please update the issue above with the correct link to you Github project link(kanban board) when I click on the link above in your issue, this is what I [ see ](https://github.com/ShaliniNayan/Capstone-Kanban )⬇️

![Screenshot_37](https://github.com/ShaliniNayan/Capstone-Kanban/assets/69638013/538763b4-5a39-43a6-9c3f-220346446130)

**Comment by ShaliniNayan** [comment]
@prolajumokeoni https://github.com/ShaliniNayan/Capstone-Kanban/projects/1

**Comment by prolajumokeoni** [comment]
Hi @Team

Your board setup is complete! 
Congratulations! 🎉 
## Highlights
 - Good setup   💯  

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification @prolajumokeoni.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
